# Site
name: "WhatsApp Groups"
title: "WhatsApp Group Links - Join & Share WhatsApp Groups"
description: "Join and share 10000+ whatsapp groups for Shayari, Masti, Jobs, Friends, News, BJP, Cricket and many more."
logo: 'assets/images/logo.png'
title_image: 'assets/images/whatsapp-group-links.jpg'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-143612101-1'
disqus: 'whatsappgroups-app'
email: 'animeshchatarjee@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
lang: "en"       # set in post to override
locale: "en_US"  # set in post to override

# Authors
authors:
  ai:
    name: Abhi I.
    display_name: AI
    avatar: 'assets/images/profile-4.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: animeshchatarjee@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "WhatsApp Geek"
  ab:
    name: Akan B.
    display_name: AB
    avatar: 'assets/images/profile-3.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: animeshchatarjee@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "WhatsApp Expert."
  db:
    name: Du B.
    display_name: DB    
    avatar: 'assets/images/profile-3.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: animeshchatarjee@gmail.com
    #web: https://www.wowthemes.net
    #twitter: https://twitter.com/wowthemesnet
    description: "Jack of all. Master of none."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-archives

# Social
#twitter:
  #username: ''
#facebook:
  #publisher: ''
  #admins: ''
  #app_id: ''

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
